language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t gifen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gifen/react-test npm test -- --coverage

after_success:
  - docker build -t gifen/complex-client ./client
  - docker build -t gifen/complex-nginx ./nginx
  - docker build -t gifen/complex-server ./server
  - docker build -t gifen/complex-worker ./worker 
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push them to docker hub
  - docker push gifen/complex-client
  - docker push gifen/complex-nginx
  - docker push gifen/complex-server
  - docker push gifen/complex-worker


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-002084661958"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"

  
